import { Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, ChevronRight, Clock3, History as HistoryIcon, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { DemoBanner, EmptyState, PageHeader, formatWorkload } from "@/components/app-ui";
import { apiClient } from "@/api";
import type { AnalysisResult } from "@/types";

export const Route = createFileRoute("/history")({ head: () => ({ meta: [{ title: "Analysis history · Cloudwise" }, { name: "description", content: "Review, revisit, and remove previous multi-cloud workload analyses." }, { property: "og:title", content: "Analysis history · Cloudwise" }, { property: "og:description", content: "Review, revisit, and remove previous multi-cloud workload analyses." }] }), component: HistoryPage });
function HistoryPage() { const [items, setItems] = useState<AnalysisResult[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { apiClient.listAnalyses().then(setItems).finally(() => setLoading(false)); }, []); async function remove(id: string) { await apiClient.deleteAnalysis(id); setItems((current) => current.filter((item) => item.id !== id)); } function clear() { if (window.confirm("Clear all saved analyses?")) { items.forEach((item) => void apiClient.deleteAnalysis(item.id)); setItems([]); } } return <div><DemoBanner /><div className="mx-auto max-w-[1440px] px-5 py-9 lg:px-8 lg:py-12"><PageHeader eyebrow="Workspace / history" title="Previous analyses" description="Revisit demo analyses and compare how your priorities change the recommendation. Saved locally in this browser." action={items.length > 0 ? <Button variant="outline" size="sm" onClick={clear}><Trash2 className="size-3.5" />Clear all</Button> : undefined} />{loading ? <div className="mt-8 grid gap-3">{[1, 2, 3].map((item) => <div key={item} className="h-24 animate-pulse rounded-lg border bg-muted" />)}</div> : items.length === 0 ? <div className="mt-8"><EmptyState icon={HistoryIcon} title="No analyses yet" description="Your saved workload comparisons will appear here." action={<Link to="/configure"><Button>Run your first analysis<ArrowRight className="size-4" /></Button></Link>} /></div> : <div className="mt-8 space-y-3">{items.map((item) => <HistoryRow key={item.id} item={item} onDelete={() => remove(item.id)} />)}</div>}</div></div>; }
function HistoryRow({ item, onDelete }: { item: AnalysisResult; onDelete: () => void }) { const candidate = (id: string) => item.candidates.find((entry) => entry.id === id); const cost = candidate(item.recommendations.lowerCost); const carbon = candidate(item.recommendations.lowerCarbon); const balanced = candidate(item.recommendations.balanced); return <div className="group rounded-lg border bg-card p-4 transition-colors hover:border-primary/40 sm:p-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-md bg-secondary text-primary"><HistoryIcon className="size-4" /></span><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{formatWorkload(item.input.workloadType)}</h2><span className="rounded-full bg-muted px-2 py-0.5 text-[10px] text-muted-foreground">{item.input.region}</span></div><p className="mt-1 flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="size-3.5" />{new Date(item.createdAt).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}<span>·</span><Clock3 className="size-3.5" />{item.input.cpuCores} vCPU / {item.input.ramGb} GB RAM</p></div></div><div className="grid grid-cols-3 gap-4 border-y py-3 lg:border-0 lg:py-0"><HistoryMetric label="Cost-focused" candidate={cost} /><HistoryMetric label="Carbon-focused" candidate={carbon} /><HistoryMetric label="Balanced" candidate={balanced} /></div><div className="flex items-center gap-2"><Link to="/results/$id" params={{ id: item.id }}><Button variant="outline" size="sm">View details<ChevronRight className="size-3.5" /></Button></Link><Button variant="ghost" size="icon" aria-label="Delete analysis" title="Delete analysis" onClick={() => { if (window.confirm("Delete this analysis?")) onDelete(); }}><Trash2 className="size-4 text-muted-foreground" /></Button></div></div></div>; }
function HistoryMetric({ label, candidate }: { label: string; candidate?: AnalysisResult["candidates"][number] | undefined }) { return <div><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 text-xs font-semibold">{candidate?.provider ?? "—"}</p><p className="metric mt-0.5 text-[10px] text-primary">{candidate ? `$${candidate.cost.value} / ${candidate.carbon.value} kg` : "No result"}</p></div>; }
