import { Link } from "@tanstack/react-router";
import { BarChart3, Check, Cloud, Database, Leaf, SearchCheck, ShieldCheck, SlidersHorizontal, Sparkles } from "lucide-react";
import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "Cloudwise · Multi-cloud sustainability analysis" }, { name: "description", content: "Explore cloud cost, carbon, and performance trade-offs in one transparent workspace." }, { property: "og:title", content: "Cloudwise · Multi-cloud sustainability analysis" }, { property: "og:description", content: "Explore cloud cost, carbon, and performance trade-offs in one transparent workspace." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: Overview,
});

const views = {
  "Cost-first": { x: 25, y: 64, provider: "Google Cloud", cost: "$150", carbon: "50 kg", note: "Lowest monthly estimate" },
  "Green-first": { x: 57, y: 28, provider: "Azure", cost: "$177", carbon: "40 kg", note: "Lowest carbon estimate" },
  Balanced: { x: 38, y: 48, provider: "Google Cloud", cost: "$150", carbon: "50 kg", note: "Strongest weighted fit" },
};
type ViewName = keyof typeof views;

function Overview() {
  const [view, setView] = useState<ViewName>("Balanced"); const selected = views[view];
  return <div className="surface-grid overflow-hidden"><section className="mx-auto max-w-[1440px] px-4 pb-12 pt-10 sm:px-6 lg:px-8 lg:pb-20 lg:pt-16"><div className="grid items-center gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:gap-16"><div><div className="inline-flex items-center gap-2 rounded-full border bg-card px-3 py-1.5 text-xs font-medium text-primary elevation-1"><span className="size-1.5 rounded-full bg-success" />Transparent demo workspace</div><h1 className="mt-6 max-w-2xl text-[2.55rem] font-semibold leading-[1.05] display-heading sm:text-6xl lg:text-7xl">Choose cloud infrastructure with the trade-offs in view.</h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground">Compare cost, carbon, and performance for one workload. Get three honest answers, not one universal winner.</p><div className="mt-8"><Button asChild size="lg" className="w-full sm:w-auto"><Link to="/configure"><Sparkles />Analyze workload</Link></Button></div><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted-foreground"><span className="flex items-center gap-2"><Check className="size-3.5 text-primary" />No account required</span><span className="flex items-center gap-2"><Check className="size-3.5 text-primary" />Every figure has context</span></div></div><ScatterPanel view={view} onView={setView} selected={selected} /></div></section><Benefits /><HowItWorks /><section className="border-t bg-card"><div className="mx-auto grid max-w-[1440px] gap-6 px-4 py-10 sm:px-6 md:grid-cols-[auto_1fr_auto] md:items-center lg:px-8"><span className="grid size-12 place-items-center rounded-lg bg-secondary text-primary"><ShieldCheck className="size-6" /></span><div><h2 className="text-lg font-semibold">Designed for transparent decisions</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Every cost and carbon figure shows its source, retrieval date, and method. Demo figures stay clearly labeled.</p></div><Button asChild variant="outline"><Link to="/history">View demo analyses</Link></Button></div></section></div>;
}

function ScatterPanel({ view, onView, selected }: { view: ViewName; onView: (view: ViewName) => void; selected: (typeof views)[ViewName] }) {
  return <div className="rounded-xl border bg-card p-4 elevation-3 sm:p-6"><div className="flex flex-col gap-4 border-b pb-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs text-muted-foreground">Cost versus carbon</p><p className="mt-1 font-semibold">API service · India</p></div><div className="grid grid-cols-3 rounded-md border p-1">{(Object.keys(views) as ViewName[]).map((item) => <button key={item} onClick={() => onView(item)} className={`min-h-10 rounded px-2 text-[11px] font-semibold transition-colors ${view === item ? "bg-secondary text-primary" : "text-muted-foreground hover:text-foreground"}`} aria-pressed={view === item}>{item}</button>)}</div></div><div className="relative mt-5 h-72 rounded-lg border bg-muted/30" role="img" aria-label={`Cost versus carbon scatter. ${selected.provider} is highlighted for ${view}.`}><span className="absolute left-3 top-3 text-[10px] text-muted-foreground">Lower carbon</span><span className="absolute bottom-3 right-3 text-[10px] text-muted-foreground">Higher cost</span><div className="absolute inset-x-8 bottom-9 top-8 border-b border-l"><div className="absolute left-1/2 top-0 h-full border-l border-dashed border-border" /><div className="absolute left-0 top-1/2 w-full border-t border-dashed border-border" />{[{ x: 24, y: 67, label: "AWS", color: "bg-provider-aws" }, { x: 38, y: 48, label: "GCP", color: "bg-provider-gcp" }, { x: 58, y: 28, label: "Azure", color: "bg-provider-azure" }].map((point) => <span key={point.label} className={`absolute grid size-9 -translate-x-1/2 translate-y-1/2 place-items-center rounded-full text-[9px] font-bold text-primary-foreground ${point.color}`} style={{ left: `${point.x}%`, bottom: `${point.y}%` }}>{point.label}</span>)}<span className="absolute size-14 -translate-x-1/2 translate-y-1/2 rounded-full border-2 border-primary bg-primary/15 transition-[left,bottom] duration-300" style={{ left: `${selected.x}%`, bottom: `${selected.y}%` }} /></div></div><div className="mt-4 grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-3"><div className="min-w-0"><p className="truncate font-semibold">{selected.provider}</p><p className="truncate text-xs text-muted-foreground">{selected.note}</p></div><div><p className="text-[10px] text-muted-foreground">Cost</p><p className="metric text-sm font-semibold">{selected.cost}</p></div><div><p className="text-[10px] text-muted-foreground">Carbon</p><p className="metric text-sm font-semibold">{selected.carbon}</p></div></div></div>;
}

function Benefits() { const benefits = [{ icon: BarChart3, title: "See cost clearly", text: "Compare like-for-like monthly estimates without switching between provider calculators." }, { icon: Leaf, title: "Treat carbon as a decision", text: "Place estimated emissions beside spend and performance, not in a separate report." }, { icon: SlidersHorizontal, title: "Make priorities explicit", text: "Change your cost, carbon, and performance weights and see the recommendation respond." }]; return <section className="border-y bg-card"><div className="mx-auto max-w-[1440px] px-4 py-12 sm:px-6 lg:px-8"><div className="grid gap-px overflow-hidden rounded-lg border bg-border lg:grid-cols-[1.25fr_0.75fr]"><article className="bg-card p-6 sm:p-8 lg:row-span-2"><span className="grid size-11 place-items-center rounded-lg bg-secondary text-primary"><benefits.0.icon className="size-5" /></span><h2 className="mt-6 text-2xl font-semibold">{benefits[0].title}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">{benefits[0].text}</p><div className="mt-8 grid grid-cols-3 gap-2" aria-hidden="true">{[62, 44, 78].map((h, i) => <div key={h} className="flex h-24 items-end rounded bg-muted p-2"><span className={`w-full rounded-sm ${i === 0 ? "bg-provider-aws" : i === 1 ? "bg-provider-gcp" : "bg-provider-azure"}`} style={{ height: `${h}%` }} /></div>)}</div></article>{benefits.slice(1).map(({ icon: Icon, title, text }) => <article key={title} className="grid grid-cols-[auto_1fr] gap-4 bg-card p-6"><span className="grid size-10 place-items-center rounded-lg bg-secondary text-primary"><Icon className="size-5" /></span><div><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div></article>)}</div></div></section>; }
function HowItWorks() { const steps = [{ icon: Cloud, title: "Describe the workload", text: "Add resources, usage, region, and performance needs." }, { icon: SearchCheck, title: "Compare the options", text: "Review aligned estimates across AWS, Google Cloud, and Azure." }, { icon: Database, title: "Choose your trade-off", text: "Use the cost, carbon, or balanced recommendation." }]; return <section className="mx-auto max-w-[1440px] px-4 py-14 sm:px-6 lg:px-8"><h2 className="text-2xl font-semibold">How it works</h2><div className="mt-7 grid gap-8 md:grid-cols-3">{steps.map(({ icon: Icon, title, text }, index) => <div key={title} className="grid grid-cols-[auto_1fr] gap-4"><span className="metric grid size-10 place-items-center rounded-full border bg-card text-sm font-semibold text-primary">{index + 1}</span><div><Icon className="size-5 text-primary" /><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div></div>)}</div></section>; }