import { Link, useLocation } from "@tanstack/react-router";
import { BarChart3, BookOpen, Check, ChevronDown, CircleHelp, Cloud, FileDown, History, Info, Leaf, Menu, Moon, Network, RefreshCw, Settings2, Sparkles, Sun, X } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { CandidateConfig, Provider, SourcedValue } from "@/types";

export const providerClass: Record<Provider, string> = { AWS: "bg-provider-aws", "Google Cloud": "bg-provider-gcp", Azure: "bg-provider-azure" };
export const providerTextClass: Record<Provider, string> = { AWS: "text-provider-aws", "Google Cloud": "text-provider-gcp", Azure: "text-provider-azure" };
export const providerShort: Record<Provider, string> = { AWS: "AWS", "Google Cloud": "GCP", Azure: "Azure" };

function ThemeToggle() {
  const [dark, setDark] = useState(false);
  useEffect(() => {
    const stored = window.localStorage.getItem("cloudwise-theme");
    const next = stored ? stored === "dark" : window.matchMedia("(prefers-color-scheme: dark)").matches;
    setDark(next); document.documentElement.classList.toggle("dark", next);
  }, []);
  function toggle() { const next = !dark; setDark(next); document.documentElement.classList.toggle("dark", next); window.localStorage.setItem("cloudwise-theme", next ? "dark" : "light"); }
  return <Button variant="ghost" size="icon" onClick={toggle} aria-label={`Use ${dark ? "light" : "dark"} mode`} title={`Use ${dark ? "light" : "dark"} mode`}>{dark ? <Sun /> : <Moon />}</Button>;
}

export function AppShell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false); const location = useLocation();
  const links = [{ to: "/", label: "Overview", icon: BarChart3 }, { to: "/configure", label: "New analysis", icon: Sparkles }, { to: "/history", label: "History", icon: History }];
  return <div className="min-h-screen bg-background"><header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur"><div className="mx-auto grid h-16 max-w-[1440px] grid-cols-[minmax(0,1fr)_auto] items-center gap-2 px-4 sm:px-6 lg:flex lg:px-8"><Link to="/" className="flex min-w-0 items-center gap-3" onClick={() => setOpen(false)}><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-primary text-primary-foreground"><Leaf className="size-5" /></span><span className="truncate text-[15px] font-semibold">cloudwise</span></Link><nav className="hidden flex-1 items-center justify-center gap-1 lg:flex">{links.map(({ to, label, icon: Icon }) => <Link key={to} to={to} activeProps={{ className: "bg-secondary text-foreground" }} className="inline-flex min-h-11 items-center gap-2 rounded-md px-3 text-sm text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"><Icon className="size-4" />{label}</Link>)}</nav><div className="flex shrink-0 items-center gap-1"><ThemeToggle /><div className="hidden items-center gap-3 lg:flex"><span className="flex items-center gap-2 text-xs text-muted-foreground"><span className="size-2 rounded-full bg-success" />Demo workspace</span><Button asChild size="sm"><Link to="/configure"><Sparkles />Run analysis</Link></Button></div><Button variant="outline" size="icon" className="lg:hidden" aria-label={open ? "Close navigation" : "Open navigation"} aria-expanded={open} aria-controls="mobile-navigation" onClick={() => setOpen((value) => !value)}>{open ? <X /> : <Menu />}</Button></div></div>{open && <nav id="mobile-navigation" className="border-t px-4 py-3 lg:hidden">{links.map(({ to, label, icon: Icon }) => <Link key={to} to={to} onClick={() => setOpen(false)} className={`flex min-h-11 items-center gap-3 rounded-md px-3 text-sm ${location.pathname === to ? "bg-secondary text-foreground" : "text-muted-foreground"}`}><Icon className="size-4" />{label}</Link>)}</nav>}</header><main>{children}</main><footer className="mx-auto flex max-w-[1440px] flex-col gap-2 border-t px-4 py-6 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><span>Cloudwise · Multi-cloud carbon and cost intelligence</span><span className="flex items-center gap-2"><CircleHelp className="size-3.5" />Transparent demo data</span></footer></div>;
}

export function DemoBanner() { return <div className="border-b border-warning/25 bg-warning/10"><div className="mx-auto flex min-h-10 max-w-[1440px] items-center gap-2 px-4 py-2 text-xs text-warning-foreground sm:px-6 lg:px-8"><Info className="size-4 shrink-0" /><strong className="shrink-0">Demo data</strong><span className="hidden truncate sm:inline">Figures are placeholders, not real prices or emissions.</span><details className="relative ml-auto"><summary className="cursor-pointer list-none font-semibold underline underline-offset-2">What is this?</summary><div className="absolute right-0 top-7 z-30 w-64 rounded-md border bg-card p-3 text-foreground elevation-2"><p>These figures let you test the experience. They do not reflect live provider pricing or emissions.</p></div></details></div></div>; }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="grid grid-cols-1 gap-5 border-b pb-8 md:grid-cols-[minmax(0,1fr)_auto] md:items-end"><div className="min-w-0"><p className="text-xs font-semibold text-primary">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold leading-tight display-heading sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></div>{action && <div className="flex flex-wrap gap-2">{action}</div>}</div>; }
export function SectionLabel({ children }: { children: ReactNode }) { return <h2 className="text-lg font-semibold">{children}</h2>; }
export function DataBadge({ value }: { value: SourcedValue }) { const label = value.dataType === "mock" ? "Demo" : `${value.dataType.charAt(0).toUpperCase()}${value.dataType.slice(1)}`; return <details className="relative inline-block"><summary className="min-h-6 list-none cursor-pointer"><Badge variant="outline" className="gap-1 border-primary/25 bg-primary/5 text-[10px] font-medium text-primary"><span className="size-1.5 rounded-full bg-primary" />{label}<ChevronDown className="size-2.5" /></Badge></summary><div className="absolute right-0 top-7 z-30 w-56 rounded-md border bg-card p-3 text-left text-xs elevation-2"><p className="font-semibold">Data transparency</p><p className="mt-2 text-muted-foreground">Source: {value.source}</p><p className="mt-1 text-muted-foreground">Retrieved: {value.retrievedAt}</p>{value.methodology && <p className="mt-1 text-muted-foreground">Method: {value.methodology}</p>}</div></details>; }
export function MetricValue({ value, decimals = 0 }: { value: SourcedValue; decimals?: number }) { return <div className="flex flex-wrap items-center gap-2"><span className="metric text-lg font-semibold">{value.value.toFixed(decimals)}</span><span className="text-xs text-muted-foreground">{value.unit}</span><DataBadge value={value} /></div>; }
export function ProviderMark({ provider }: { provider: Provider }) { return <span className="flex min-w-0 items-center gap-2"><span className={`grid size-8 shrink-0 place-items-center rounded-md text-[10px] font-bold text-primary-foreground ${providerClass[provider]}`}>{providerShort[provider]}</span><span className="truncate font-semibold">{provider}</span></span>; }
export function CandidateCard({ candidate, recommended }: { candidate: CandidateConfig; recommended?: string[] | undefined }) { const tags = recommended?.filter(Boolean) ?? []; return <div className={`rounded-lg border bg-card p-5 elevation-1 ${tags.length ? "border-primary/50" : ""}`}><div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-3"><ProviderMark provider={candidate.provider} />{tags.length > 0 && <div className="flex flex-wrap justify-end gap-1">{tags.map((tag) => <Badge key={tag} className="bg-primary/10 text-primary hover:bg-primary/10"><Check className="size-3" />{tag}</Badge>)}</div>}</div>{!candidate.compatible ? <div className="mt-6 rounded-md bg-muted px-3 py-4 text-sm text-muted-foreground">No compatible configuration for this workload.</div> : <><p className="mt-5 text-sm font-medium">{candidate.service}</p><p className="mt-1 text-xs text-muted-foreground">{candidate.region} · {candidate.cpuCores} vCPU · {candidate.ramGb} GB RAM</p><div className="mt-5 grid grid-cols-2 gap-x-4 gap-y-5"><div><p className="text-xs text-muted-foreground">Monthly cost</p><p className="metric mt-1 text-xl font-semibold">${candidate.cost.value.toLocaleString()}<span className="text-xs font-normal text-muted-foreground"> / mo</span></p></div><div><p className="text-xs text-muted-foreground">Overall score</p><p className="metric mt-1 text-xl font-semibold text-primary">{candidate.overallScore.toFixed(0)}<span className="text-xs font-normal text-muted-foreground"> / 100</span></p></div><div><p className="text-xs text-muted-foreground">Carbon</p><p className="metric mt-1 font-semibold">{candidate.carbon.value} <span className="text-xs font-normal text-muted-foreground">kg CO₂e</span></p></div><div><p className="text-xs text-muted-foreground">Performance</p><p className="metric mt-1 font-semibold">{candidate.performance.value} <span className="text-xs font-normal text-muted-foreground">/ 100</span></p></div></div></>}</div>; }
export function EmptyState({ icon: Icon = Network, title, description, action }: { icon?: typeof Network; title: string; description: string; action?: ReactNode }) { return <div className="flex min-h-72 flex-col items-center justify-center rounded-lg border border-dashed bg-card/50 px-6 text-center"><svg aria-hidden="true" viewBox="0 0 160 90" className="h-24 w-40 text-primary"><path d="M22 67h116M44 65V43m36 22V21m36 44V35" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><circle cx="44" cy="39" r="8" fill="currentColor" opacity=".2"/><circle cx="80" cy="17" r="8" fill="currentColor" opacity=".35"/><circle cx="116" cy="31" r="8" fill="currentColor" opacity=".55"/></svg><span className="sr-only"><Icon /></span><h2 className="mt-3 text-lg font-semibold">{title}</h2><p className="mt-2 max-w-sm text-sm text-muted-foreground">{description}</p>{action && <div className="mt-5">{action}</div>}</div>; }
export function ShellIconButton({ label, children, onClick }: { label: string; children: ReactNode; onClick?: () => void }) { return <Button type="button" variant="outline" size="icon" aria-label={label} title={label} onClick={onClick}>{children}</Button>; }
export const icons = { chart: BarChart3, cloud: Cloud, file: FileDown, book: BookOpen, refresh: RefreshCw, settings: Settings2 };
export function formatWorkload(value: string) { return value.split("-").map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`).join(" "); }