import { Link, useLocation } from "@tanstack/react-router";
import { ArrowRight, BarChart3, BookOpen, Check, ChevronDown, CircleHelp, Cloud, FileDown, History, Leaf, Menu, Network, RefreshCw, Settings2, Sparkles, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { CandidateConfig, Provider, SourcedValue } from "@/types";

export const providerClass: Record<Provider, string> = { AWS: "bg-provider-aws", "Google Cloud": "bg-provider-gcp", Azure: "bg-provider-azure" };
export const providerTextClass: Record<Provider, string> = { AWS: "text-provider-aws", "Google Cloud": "text-provider-gcp", Azure: "text-provider-azure" };
export const providerShort: Record<Provider, string> = { AWS: "AWS", "Google Cloud": "GCP", Azure: "Azure" };

export function AppShell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false); const location = useLocation();
  const links = [{ to: "/", label: "Overview", icon: BarChart3 }, { to: "/configure", label: "New analysis", icon: Sparkles }, { to: "/history", label: "History", icon: History }];
  return <div className="min-h-screen bg-background"><header className="sticky top-0 z-40 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-5 lg:px-8"><Link to="/" className="flex items-center gap-3" onClick={() => setOpen(false)}><span className="grid size-9 place-items-center rounded-lg bg-primary text-primary-foreground"><Leaf className="size-5" /></span><span className="hidden text-[15px] font-semibold tracking-tight sm:block">cloudwise</span></Link><button aria-label="Toggle navigation" className="inline-flex size-10 items-center justify-center rounded-md border md:hidden" onClick={() => setOpen((value) => !value)}>{open ? <X className="size-4" /> : <Menu className="size-4" />}</button><nav className="hidden items-center gap-1 md:flex">{links.map(({ to, label, icon: Icon }) => <Link key={to} to={to} activeProps={{ className: "bg-secondary text-foreground" }} className="inline-flex items-center gap-2 rounded-md px-3 py-2 text-sm text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"><Icon className="size-4" />{label}</Link>)}</nav><div className="hidden items-center gap-3 md:flex"><span className="flex items-center gap-2 text-xs text-muted-foreground"><span className="size-2 rounded-full bg-success" />Demo workspace</span><Link to="/configure"><Button size="sm"><Sparkles className="size-3.5" />Run analysis</Button></Link></div></div>{open && <nav className="border-t px-5 py-3 md:hidden">{links.map(({ to, label, icon: Icon }) => <Link key={to} to={to} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-md px-3 py-3 text-sm ${location.pathname === to ? "bg-secondary text-foreground" : "text-muted-foreground"}`}><Icon className="size-4" />{label}</Link>)}</nav>}</header><main>{children}</main><footer className="mx-auto flex max-w-[1440px] flex-col gap-2 border-t px-5 py-6 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>Cloudwise · Multi-cloud carbon & cost intelligence</span><span className="flex items-center gap-2"><CircleHelp className="size-3.5" />Built for exploration with transparent demo data</span></footer></div>;
}

export function DemoBanner() { return <div className="flex items-start gap-3 border-b border-warning/25 bg-warning/10 px-4 py-3 text-sm text-warning-foreground"><span className="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-warning text-warning-foreground"><span className="text-[11px] font-bold">i</span></span><p><strong>Demo data:</strong> figures are placeholders for testing the interface, not real prices or emissions.</p></div>; }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="flex flex-col gap-5 border-b pb-7 md:flex-row md:items-end md:justify-between"><div><p className="metric text-[11px] font-medium uppercase tracking-[0.12em] text-primary">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold display-heading sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></div>{action}</div>; }
export function SectionLabel({ children }: { children: ReactNode }) { return <h2 className="text-sm font-semibold tracking-tight">{children}</h2>; }
export function DataBadge({ value }: { value: SourcedValue }) { const label = value.dataType === "mock" ? "Demo" : value.dataType[0].toUpperCase() + value.dataType.slice(1); return <details className="relative inline-block"><summary className="list-none cursor-pointer"><Badge variant="outline" className="gap-1 border-primary/25 bg-primary/5 px-1.5 py-0 text-[10px] font-medium text-primary"><span className="size-1.5 rounded-full bg-primary" />{label}<ChevronDown className="size-2.5" /></Badge></summary><div className="absolute right-0 top-6 z-20 w-64 rounded-md border bg-card p-3 text-left text-xs shadow-lg"><p className="font-semibold">Data transparency</p><p className="mt-2 text-muted-foreground">Source: {value.source}</p><p className="mt-1 text-muted-foreground">Retrieved: {value.retrievedAt}</p>{value.methodology && <p className="mt-1 text-muted-foreground">Method: {value.methodology}</p>}</div></details>; }
export function MetricValue({ value, decimals = 0 }: { value: SourcedValue; decimals?: number }) { return <div className="flex items-center gap-2"><span className="metric text-lg font-semibold">{value.value.toFixed(decimals)}</span><span className="text-xs text-muted-foreground">{value.unit}</span><DataBadge value={value} /></div>; }
export function ProviderMark({ provider }: { provider: Provider }) { return <span className="flex items-center gap-2"><span className={`grid size-7 place-items-center rounded-md text-[10px] font-bold text-primary-foreground ${providerClass[provider]}`}>{providerShort[provider]}</span><span className="font-semibold">{provider}</span></span>; }
export function CandidateCard({ candidate, recommended }: { candidate: CandidateConfig; recommended?: string[] }) { const tags = recommended?.filter(Boolean) ?? []; return <div className={`rounded-lg border bg-card p-5 ${tags.length ? "border-primary/50 ring-1 ring-primary/10" : ""}`}><div className="flex items-start justify-between gap-3"><ProviderMark provider={candidate.provider} />{tags.length > 0 && <div className="flex flex-wrap justify-end gap-1">{tags.map((tag) => <Badge key={tag} className="bg-primary/10 text-primary hover:bg-primary/10">{tag}</Badge>)}</div>}</div>{!candidate.compatible ? <div className="mt-7 rounded-md bg-muted px-3 py-4 text-sm text-muted-foreground">No compatible configuration for this workload.</div> : <><p className="mt-5 text-sm font-medium">{candidate.service}</p><p className="mt-1 text-xs text-muted-foreground">{candidate.region} · {candidate.cpuCores} vCPU · {candidate.ramGb} GB RAM</p><div className="mt-5 grid grid-cols-2 gap-y-4"><div><p className="text-xs text-muted-foreground">Est. monthly cost</p><p className="metric mt-1 text-xl font-semibold">${candidate.cost.value.toLocaleString()}<span className="text-xs font-normal text-muted-foreground"> / mo</span></p></div><div><p className="text-xs text-muted-foreground">Overall score</p><p className="metric mt-1 text-xl font-semibold text-primary">{candidate.overallScore.toFixed(0)}<span className="text-xs font-normal text-muted-foreground"> / 100</span></p></div><div><p className="text-xs text-muted-foreground">Carbon footprint</p><div className="mt-1"><MetricValue value={candidate.carbon} /></div></div><div><p className="text-xs text-muted-foreground">Performance</p><div className="mt-1"><MetricValue value={candidate.performance} /></div></div></div></>}</div>; }
export function EmptyState({ icon: Icon = Network, title, description, action }: { icon?: typeof Network; title: string; description: string; action?: ReactNode }) { return <div className="flex min-h-64 flex-col items-center justify-center rounded-lg border border-dashed bg-card/50 px-6 text-center"><span className="grid size-11 place-items-center rounded-full bg-secondary text-primary"><Icon className="size-5" /></span><h2 className="mt-4 text-base font-semibold">{title}</h2><p className="mt-2 max-w-sm text-sm text-muted-foreground">{description}</p>{action && <div className="mt-5">{action}</div>}</div>; }
export function ShellIconButton({ label, children, onClick }: { label: string; children: ReactNode; onClick?: () => void }) { return <Button type="button" variant="outline" size="icon" aria-label={label} title={label} onClick={onClick}>{children}</Button>; }
export const icons = { arrow: ArrowRight, chart: BarChart3, cloud: Cloud, file: FileDown, book: BookOpen, refresh: RefreshCw, settings: Settings2 };
export function formatWorkload(value: string) { return value.split("-").map((part) => part[0]?.toUpperCase() + part.slice(1)).join(" "); }
